### ISSUE TITLE
Rename function should be in the 3-dot menu of the share link

### ISSUE THREAD

**Issue by jancborchardt** [DecaTec/sharerenamer#1]
Especially for Nextcloud 14 compatibility, the rename function should move into the 3-dot menu of the share link. If you check out Nextcloud 14 you will see the layout changed:
![screenshot from 2018-08-14 15-59-06](https://user-images.githubusercontent.com/925062/44096190-fe35e554-9fda-11e8-96dc-c8807fcb21f7.png)

So there should be an entry for "Change link" below "Copy link" which then opens the text field.

**Comment by DecaTec** [comment]
Problem is that the share link text box is hidden by default now.
Already working on a solution for NC 14. Maybe the link text box shold be visible by default if the app is installed/enabled.

**Comment by DecaTec** [comment]
Works with NC 14 now.
Still needs some polishing while I wait for the certificate request so that it can be released in the NC app store.

**Comment by jancborchardt** [comment]
>  Maybe the link text box shold be visible by default if the app is installed/enabled.

No, there should be no box, as there is simply a "copy link" button. :)

When your app is enabled, as said:

> So there should be an entry for "Change link" below "Copy link" which then opens the text field.

That should happen inside the popover, much like the "Password protect" function.

**Comment by DecaTec** [comment]
> That should happen inside the popover, much like the "Password protect" function.

Already done, there is only a rename button below the copy button. By pressing the button, the renaming fields are set visible in the popover menu.
