### ISSUE TITLE
Long share Names

### ISSUE THREAD

**Issue by JazMTaz** [DecaTec/sharerenamer#12]
ShareRenamer lets me create a long share name (35 character places), and when I select copy link icon, it copies the entire long link which doesn't work. The original link will work however if I truncate the url to 32 character places, so the link that is created has actually already been truncated to 32 character places, but the copy link icon generates an incorrect url.

**Comment by DecaTec** [comment]
In the database, the column containing the shared links is defined as varchar(32). So you'll get a DB error message when the link is longer than 32 chars.

Fixed with https://github.com/DecaTec/sharerenamer/commit/aff6fe4c705a28b7b9455464c9c8551e7b1091ab
The app will be updated in a few days.

**Comment by DecaTec** [comment]
New Version 2.4.0 released:
https://github.com/DecaTec/sharerenamer/releases/tag/2.4.0

Should already be available in the app store.

**Comment by JazMTaz** [comment]
Great job guys, thanks
