### ISSUE TITLE
Able to rename "Share Link" itself to meaninful text

### ISSUE THREAD

**Issue by jiansong** [DecaTec/sharerenamer#16]
NextCloud supports to add multiple "Share Link"(s), imagining a user created several Share Link for the same resource, but having different permissions, they all displayed same. When this user wants to edit one of them, will have to click/and open them one by one to find out the link needed to edit.

If user can name those "Share Link"(s) to different meaningful text, will be a great improvement to the experiment.

It will be something like this:
- Share link for Alice (drop folder)
- Share link for Bob (read only)
- Share link for John (full access)

**Comment by DecaTec** [comment]
I think that this is a general problem of creating multiple links for one file/folder, because non of these can be given a meaningful name.
This is not specific to this app.

So please feel free to crate an issue about that usability optimization in the Nextcloud repository.

**Comment by jiansong** [comment]
Ok, thanks for the feedback!
