### ISSUE TITLE
[Feature Request] Add support for YOURLS via API

### ISSUE THREAD

**Issue by sunjam** [DecaTec/sharerenamer#19]
Hi, thanks for keeping this great app alive!

Please consider adding the ability to send a URL to a [YOURLS](http://yourls.org/) instance via their API, which is fully open source and coded in PHP.
[Here is the API documentation](https://api.yourls.org/doc).  And [more general API and Hook documentation](https://github.com/YOURLS/YOURLS/wiki) + info on the [Passwordless API](https://github.com/YOURLS/YOURLS/wiki/PasswordlessAPI)

Thanks either way!

**Comment by DecaTec** [comment]
I don't think that it is a good idea to implement features relying on external services (even if these are self hosted).
The app itself should only rely on the Nextcloud ecosystem.
