### ISSUE TITLE
Delete Links

### ISSUE THREAD

**Issue by Judocrafter** [DecaTec/sharerenamer#22]
How can i delete a Link?

I deleted a folder that was still shared and now I cannot use the same link

Thank you

**Comment by DecaTec** [comment]
A shared link is kind of a property of a file or folder. If you delete a file/folder, it's still there - in the trash bin. When the file is restored from the trash, the shared link will work again.

In order to re-use a shared link name, delete the file, empty the trash bin and wait for the next tick of the cron job.

**Comment by Judocrafter** [comment]
I have now removed all the shared folders, deleted them and emptied the trash. I also started the cron job manually. Unfortunately did not help. I even removed and added the app. What else can I do?

**Comment by DecaTec** [comment]
The deleted shared link may not be released immediately after the cron job was run, but it should be released some time later. I've set the cron jon to run every 5 minutes and have to wait for approximately  10 minutes so that I can rename a link to the same name.

If this also doesn't work for you: Du you use MySQL/MaraiDB or PostgreSQL as database?

**Comment by Judocrafter** [comment]
My cron job run every 15 minutes.

I've tried it several times all morning.

I use MySQL/MariaDB database

Thank you

Am 2019-12-16 12:54, schrieb DecaTec:

**Comment by DecaTec** [comment]
With MySQL/MariaDB there should be no problem at all (the last update fixed an issue with PostgreSQL). 

Unfortunately,  I cannot reproduce this problem. So we have to seek for any hints:

- Are there any log entries regarding shared links and/or the deleted folders?
- Make sure that the files got properly deleted from the trash bin. Sometimes the files/folders remain in the trash bin when you delete all contents of the trash bin at once. In this case, delete the file/folders one after another.
- Take a look at the database itsself: `SELECT token FROM oc_share;` should give you a list of active shared links. This list should *not* contain the link you already have deleted.

**Comment by Judocrafter** [comment]
I found it on the database directly.

How can i delete them now?
Thank you for your help.
![0CF49E4F-80E6-4F28-B1C4-E030120D6A10](https://user-images.githubusercontent.com/42749857/70975460-44431e80-20aa-11ea-9c69-888e5304a97e.jpeg)

**Comment by DecaTec** [comment]
Before deleting it in the database directly (`DELETE * FROM oc_share WHERE token = <token>;`), we should find out why the enmtries get not deleted automatically.

I guess the cron job is not running correctly. Sharerenamer does not delete the shared links by itself, this is all done byNC's cron job.
Please try the following:
- Create a shared link for a folder.
- *Do not* use Sharerenamer to rename the share, but note the share's token.
- Take a look at the table oc_share -> you should find the token of the sahre you just created.
- Delete the sahred folder and empty trash bin.

I guess that this share also doesn't get cleaned up and remains in the oc_share table.
Then I would check the cron jobs log (to be found in the syslog), if there are any messages regarding errors of the NC cron job.

**Comment by Judocrafter** [comment]
Hello Thank you for your help.
 It looks like it's really up to the cron job. I deleted a token directly in the database, after which I was able to use it again.

 Can someone help me how to set it up correctly? I installed the Nextcloud server on my Synologx Nas.

 I am currently running the following script: curl --insecure https: //localhost/volume1/web/cron.php

Is this correct?

 Many thanks for the help.

--------------------------------

Domenik Vogel
Hügelstrasse 12a
9200 Gossau
Mobile +41 79 937 35 41
Am 17. Dez. 2019, 12:39 +0100 schrieb DecaTec <notifications@github.com>:

**Comment by DecaTec** [comment]
OK, then it seems to be the cron job causing these issues.

Why are you using webcron? Don't you have access to "real" cron jobs on your synology?
Usually you edit your crontab, as explained [here](https://docs.nextcloud.com/server/17/admin_manual/configuration_server/background_jobs_configuration.html).
You should only use webcron if there are no other possibilities (e.g. on shared hosting).

**Comment by Judocrafter** [comment]
I set it up locally.
Can you tell me what to do with Synology's Task Scheduler?

Sorry, I don't know enough about this.

Thank you

Am 2019-12-19 16:52, schrieb DecaTec:

**Comment by DecaTec** [comment]
Sorry, I don't have a Synology NAS.
But can't you connect to your NAS using SSH and create a cronjob in the crontab?
