### ISSUE TITLE
Unable to delete shares or reuse renamed share names

### ISSUE THREAD

**Issue by BreakfastSerial** [DecaTec/sharerenamer#23]
I'm using Nextcloud 17.0.0 with ShareRenamer 2.7.3.

I've previously created some shares and renamed them with the app. These shares have since been removed as shares, reshared and the directories are deleted. I've also removed the from the "Deleted files", as it was the problem on other issues posted here.

Now if I create a new directory, with the same name as a previous share, it immediately shows up under "Shares" (Menu on the left) and I can not reuse any share names. 

> Link 'test' already exists. Please choose another link name.

How can I fix this behavior?

**Comment by DecaTec** [comment]
The link seems to be still part of the system.
To make sure that the link doesn't exist anymore, take a look at NC's database:
`SELECT token FROM oc_share;`

Is the link in question still listed here?

**Comment by BreakfastSerial** [comment]
There's definitely no other user sharing links, for now it's just a single user test instance. The shares in question still appear in the database. There are some randomly named shares and some of which I renamed with the app.

```
AWqBj6m7YYMkojp
GBTSMxgBNsxQqG
c7YegiYaLnZLQ6K
share
kc5ojE89mLDZwgF
test
help
```

**Comment by DecaTec** [comment]
Make sure you deleted the shared files/folders from the trash bin. Double check: After the trash bin was emptied, call it again (sometimes it says that all was deleted, but on the next call of the trash bin,the files are still there).

Usually, the (deleted) shared links are removed by the cron job. So how did you set up your cron job (AJAX, Webcron, cron)?

**Comment by BreakfastSerial** [comment]
I double checked, there are no files/folders in the trash bin.

> the (deleted) shared links are removed by the cron job

I do not recall setting up such a cron job. Sounds like there is a specific job that has to be configured explicitly. What task are you referring to? I guess this would be my problem then.

**Comment by DecaTec** [comment]
Here you can find the instructions on how to set up a cron Job for NC: https://docs.nextcloud.com/server/stable/admin_manual/configuration_server/background_jobs_configuration.html

Important: Has to he as real cron Job (no AJAX, no web cron).

**Comment by BreakfastSerial** [comment]
So out of the box, NC never deletes any share _name_, which in combination with the add-in, leads to this issue. Am I understanding this correctly? If so, it sounds like my issue should be pretty common, right?

Thank you for the link to the cron job configuration! Any suggestions on how to define the job to only delete unused share names?

**Comment by DecaTec** [comment]
That would be my guess that the old links don't get deleted due to no cron job running.

Anyway, you should set up a cron job for the backgroud tasks in NC.
So there's no way of defining a backgroud job just for deleting old share links. Simply set up a "default" NC cron job.

**Comment by BreakfastSerial** [comment]
Thank you very much for your input! I'll set that up as soon as possible and will report back with the results, if any new issues arise.
