### ISSUE TITLE
Reuse of a Share Name

### ISSUE THREAD

**Issue by SvenWagnerOZ** [DecaTec/sharerenamer#25]
Hello, 
many thanks for your great work with this tool. 
Today we have an issue with the reuse of a share name. First, we had a group folder wich was shared like a simple dropit folder. We gave it a simple share name. Because we had some issues with the folder we decide to unshare and delete it. After that we created a new normal folder and shared as a dropit folder too. As we tryed to rename the share identically with the name of the deleted groupfolder share name before, we get the message that the share name is allready used.
How can we reuse a share name such as in our case after unshared an other share?

**Comment by DecaTec** [comment]
Could you please have a look at the NC database:
```
SELECT token FROM oc_share;
```

Is the old (deleted) share from the group folder still present in the database table?
How you configured the NC cron job (cron, webcron, AXJAX)?

**Comment by SvenWagnerOZ** [comment]
I checked it. The cron job is configured with cron. The time for cron was set up to 15 Minutes. So that could be the reason for my issue. While i wrote this case here an github the problem was cleared automaticaly. 
Today, as i watched into the DB Table i could only find the last renamed share name, not the old one. Now i´ve changed the cron time to 5 minutes.

Many thanks for your support from my side. I wish you the best.

Byby

**Comment by DecaTec** [comment]
Yes, the shared links not used anymore are deleted by the cron job. You always have to wait a few minutes in order to reuse a shared (and deleted) link.
