### ISSUE TITLE
NextCloud (NC) 19

### ISSUE THREAD

**Issue by HieronymusCH** [DecaTec/sharerenamer#28]
Does it work for you?
The  ShareRenamer 2.7.3 is marked as installed and active on my NextCloud 19.0.0 but it doesn't show up in the detail view of a file.

**Comment by larp-welt** [comment]
Duplicate of #21

**Comment by HieronymusCH** [comment]
Thanks, I close it.

**Comment by julpec** [comment]
I don't understand the link with #21 
For me, it's the same : NC19 and ShareRenamer 2.7.3 and it doesn't show up.
Is there something else to do to make it works ?

**Comment by julpec** [comment]
Same with other instance of NC, v18
