### ISSUE TITLE
Are old renamed links still working after update?

### ISSUE THREAD

**Issue by angerized** [DecaTec/sharerenamer#33]
Hello,

I know that sharerenamer does not work for new links with NC18+, but will updating NC17 retain current working/renamed links?

Not really an issue, but we have customers that fear that updating will break their current links.

Kind regards.

**Comment by DecaTec** [comment]
A renamed link is technically the same as a "normal" shared link, so updates will not break existing (renamed) links.
But these links cannot be renamed anymore if NC version > 17

**Comment by angerized** [comment]
Thank you for the reply :)
