### ISSUE TITLE
Rename Share Link in Gallery

### ISSUE THREAD

**Issue by noledge** [DecaTec/sharerenamer#5]
It would be a great feature, if the share renamer would not only work in "file" mode, but also in "gallery" mode.

It does work with renaming it in "file" mode and using/copying the link in gallery mode. But you can't generate/rename the link directly in gallery mode.

For example:
* renaming https://nextcloud/s/waytoolongrandomlink to https://nextcloud/s/test123 works
* using https://nextcloud/apps/gallery/s/test123 instead of https://nextcloud/apps/gallery/s/waytoolongrandomlink works then
* but making https://nextcloud/apps/gallery/s/waytoolongrandomlink to https://nextcloud/apps/gallery/s/test123 directly is not possible, because there is no share link rename button in the share menu in gallery mode

**Comment by DecaTec** [comment]
With the next release you will be able to rename links in the Gallery app too.

**Comment by DecaTec** [comment]
New version available in store.
