### ISSUE TITLE
sharing via email won't use the nuew changes document ID

### ISSUE THREAD

**Issue by Django-BOfH** [DecaTec/sharerenamer#6]
I changed the share token to a human readable word. All works fine, exception one thing!

I'f I copy the new link the new human readable accesstoken/name ist copied, but If I klcik on share via eMail, the old share token will be used! :/

**Comment by DecaTec** [comment]
Fixed with https://github.com/DecaTec/sharerenamer/commit/69f6e04145bd22c2415ec57eae068fe8072e3576

Preparing new release...
